name: instagram_clone_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.8.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.7.7
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.7
  image_picker: ^1.1.1
  intl: ^0.19.0
  provider: ^6.0.1
  uuid: ^4.4.0
  curved_navigation_bar: ^1.0.3
  curved_labeled_navigation_bar: ^2.0.2
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  flip_card: ^0.7.0
  google_sign_in: ^6.1.6
  camera: ^0.11.0
  path_provider: ^2.1.3
  path: ^1.9.0
  tflite_flutter: ^0.10.4
  image: ^3.0.1
  geolocator: ^12.0.0
  url_launcher: ^6.2.6
  firebase_app_check: ^0.2.2+7
  flutter_image_compress: ^2.3.0
  flutter_spinkit: ^5.2.1
  sign_in_with_apple: ^6.1.1
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.3
  photo_view: ^0.15.0
  flutter_carousel_widget: ^2.2.0
  flutter_iconly: ^1.0.2
  google_fonts: ^5.1.0
  badges: ^3.1.1
  timelines: ^0.1.0
  easy_stepper: ^0.7.3
  tflite: ^1.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/services/

    - assets/bokchoymodel.tflite
    - assets/petchay_labels.txt
    - assets/images/farmer-icegif-5.gif
    - assets/images/bokchoyt.gif
    - assets/images/plant1.gif
    - assets/images/aboutus.gif
    - assets/images/aboutus2.png
    - assets/images/aboutus3.gif
    - assets/images/botanist.gif
    - assets/images/bot.gif
    - assets/images/dragon.gif
    - assets/images/plantbg.gif
    - assets/images/doctor2.gif
    - assets/images/scanning.gif
    - assets/images/uploading.gif
    - assets/images/Aimage.gif
    - assets/images/FAQ.gif
    - assets/images/calculate.gif
    - assets/logo.png

